name: custom_file_picker
description: "The file opener hierarchy system allows custom file hierarchies that must not match the running device file system."
version: 0.0.1
homepage: https://github.com/JayKay135/custom_file_picker

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  collection: ^1.18.0
  desktop_multi_window: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics:
  - widgets

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/folder_icon.png
    - assets/images/text_icon.png
    - assets/images/image_icon.png
    - assets/images/arrow.png
    - assets/images/urdf_icon.png