name: custom_file_picker
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  desktop_multi_window: ^0.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/folder_icon.png
    - assets/images/folder_icon2.png
    - assets/images/text_icon.png
    - assets/images/image_icon.png
    - assets/images/arrow.png
    - assets/images/urdf_icon.png